### ISSUE TITLE
ChoiceTable Change: Other Option

### ISSUE THREAD

**Issue by shakty** [kecerit/trialgame#18]
Hi Kerem,

I will review  in the detail and close the other issues this week, but I don't expect any more work on those.

Since you are now a widget master, could you help me with a change to the ChoiceTable widget?

The ChoiceTable is really common, in fact is now the default widget inside the forms option of the ChoiceManager. So this is going to be an impactful change.

ChoiceTable allows for multiple-choice questions. Very often, one needs to have the option "Other" and an additional input box. This is now done by creating an hidden custom input element and then adding an onclick listener. See here:

https://github.com/nodeGame/survey/blob/main/game/client_types/player.js#L121

However, it is a standard task and it could become an option of ChoiceTable. Can you create that option?

It should behave like this:

- other: true: adds an "Other" choice as last choice
- other: 'CustomInput': adds "Other" choice AND a CustomInput widget under the choicetable (initially hidden)
- other: { ... }: ads "Other" choice AND adds a CustomInput widget with configuration options specified in that object.

The text "Other" should be customizable as a text property (in the texts object).

To implement this, you may copy the file ChoiceTable from here:

https://github.com/nodeGame/nodegame-widgets/blob/master/widgets/ChoiceTable.js

into your repository, load it like you did for Dropdown, and modify it. You can also rename it to ChoiceTable2 (and all instances inside the file) to keep both the old and the new ChoiceTable alive.

We will need to modify a few other methods (e.g., getValues), but for now let's just get the options and display logic working.

It would be great if you could deliver something this week already. Let me know if you have questions or have time conflicts.

Cheers,
Stefano

**Comment by kecerit** [comment]
Hi Stefano, 

I added an other option in ChoiceTable according to your specifications. It is working. I did not make any changes in getValues() or any other method. 

Best,
Kerem

**Comment by shakty** [comment]
Thanks. I did not check the changes in the code in details, mainly its functionality for now. It looks good, but:

- the custominput should be hidden also if the user deselect 'Other'
- 'Other' should not be hardcoded, but fetched from the texts object
- I would assume that custominput should take the "required" value of choicetable as default. So if choicetable is required custominput also is. What do you think?

The getvalues method should get the value of the custom input and return it as the main value of the widget. I am not sure what is the best approach. Should it return 'Other / customvalue' or 'customvalue' ? Or something else?

**Comment by kecerit** [comment]
Hi Stefano, 

I fixed the deselect issue. 

I agree with you on the "required" value. Now if no options are specified by the user ( other: "CustomInput" ), custominput takes the "required" value of choicetable as default. But if user defines any options ( other: {...}) , the "required" value  also must be defined by the user (as with the all other options for customInput). I will change it to if undefined take the "required" value of choicetable as default. Should I also define any other default options like this ?  

For the getvalues method, I thought getvalues().choice can get the position of the "other" and getvalues().value can get the value entered in the customInput.

**Comment by kecerit** [comment]
Hi Stefano, 

I made changes in the getValues and verifyChoice to integrate the custom input. Some changes are:

- getvalues().choice gets the position of the "other" and getvalues().value gets the value entered in the customInput.
- if every condition is satisfied in the main question (isCorrect: true), isCorrect gets the value of the customInput's isCorrect. 
- Now you cannot define both correctChoice and other at the same time.

I tried the changes in multiple scenarios and there seems to be no errors. I think  couple of other methods such as Reset and setValues also need adjustments, I will look into that now.

Best,
Kerem

**Comment by shakty** [comment]
Thanks for this!

Here are my comments. 

- If there is no mainText specified for CustomInput it takes a default "text": Please specify. (to be defined in the texts object).
-  Make sure to keep nice indentation and formatting. For instance, this is quite a mess:

```js
 if (that.customInput) {
            if (value === len - 1 && !that.isChoiceCurrent(value)) that.customInput.show();
            else if (that.selectMultiple && !that.customInput.isHidden() &&
            value !== len - 1) that.customInput.show();
            else that.customInput.hide();
            }
```
and this is hard to read:

```js
if (this.customInput &&
               !this.customInput.getValues().isCorrect &&
               !this.customInput.isHidden()) {
                this.unhighlight();
              }
              else this.setError(this.getText('error', obj.value));
```
One-liners if-else should be used only if both if and else are one-liners. Leave one empty line if the if conditions span over multiple lines.

- Why are you not allowing correctChoice with other option? It should still be doable.

I will check the other methods now.

**Comment by shakty** [comment]
Yes, both reset and setValues need updats. They are easy luckily.

- reset: call custominput.reset(), if a custominput is defined.
- setValues: right at the end, after textarea checks, see if the "Other" option was selected (or if custominput.isHidden() is false), if so add some random text, using custominput.setValues({value: 'xxx'});

**Comment by shakty** [comment]
Also write the doc:

```
    /**
     * ### ChoiceTable.setCustomInput
     *
     * Set Custom Input widget.
     *
     */
```

**Comment by kecerit** [comment]
Hi Stefano, 

I made the changes following your comments.  Also now the widget allows correctChoice with other option. 

Best,
Kerem

**Comment by shakty** [comment]
Thanks, it took me a while to review it, because the changes were complex. 
In general, it was OK in terms of functionalities. However, I made several improvements to shorten the code. If interested, you can check the current version. I have already merged it in nodegame-widget, thanks for being a contributor!

**Comment by shakty** [comment]
One thing to pay attention in the future is that the indentation is 4 spaces, not 2.

**Comment by shakty** [comment]
It seems there is a strange bug: if I go back using the "BackButton" widget (also in the repo). The widget adds again the "Other" option, so there is many "Other" option. I am not sure why it is happening.

**Comment by kecerit** [comment]
Hi Stefano, 

Thank you, I checked the changes you made and I am sorry that you need to make that many.  The bug related to the "BackButton" happened because of how I added the "other" choice. 

I am adding an "other" choice to the choices array provided by the user in the setChoices(), if option other is true. Since I do not drop this added "other"  later, there on choices array includes the "other" added by us.  Later when setChoices() called again in such a case like using backbutton, it adds another "other" to the choices which was already modified by us in the first  setChoices() call.

I fixed the issue by adding two lines to setChoices() that checks the existence of and drop the previously added "others" before adding one to the end of the array.  I did it this way as I thought we always want "other" as the last choice, not included in the shuffle. 

```js
        var indexOther = choices.indexOf(this.getText('other'));
        if (this.other && indexOther >= 0) choices.splice(indexOther,1);
```
Best,
Kerem
